export const constructorMap = {
  'giovinazzi': 'alfa',
  'raikkonen': 'alfa',
  'gasly': 'alphatauri',
  'kvyat': 'alphatauri',
  'vettel': 'ferrari',
  'leclerc': 'ferrari',
  'kevin_magnussen': 'haas',
  'grosjean': 'haas',
  'sainz': 'mclaren',
  'norris': 'mclaren',
  'hamilton': 'mercedes',
  'bottas': 'mercedes',
  'perez': 'racing_point',
  'stroll': 'racing_point',
  'max_verstappen': 'red_bull',
  'albon': 'red_bull',
  'ricciardo': 'renault',
  'ocon': 'renault',
  'russell': 'williams',
  'latifi': 'williams'
};

export const constructorColors = {
  'alfa': 'rgba(155, 0, 0, 0.8)',
  'alphatauri': 'rgba(70, 155, 255, 0.8)',
  'ferrari': 'rgba(220, 1, 1, 0.8)',
  'haas': '	rgba(190, 159, 89, 0.8)',
  'mclaren': 'rgba(255, 135, 0, 0.8)',
  'mercedes': '	rgba(0, 210, 190, 0.8)',
  'racing_point': 'rgba(245, 150, 200, 0.8)',
  'red_bull': 'rgba(30, 65, 255, 0.8)',
  'renault': 'rgba(255, 245, 0, 0.8)',
  'williams': 'rgba(245, 245, 245, 0.8)',
};
